export const SIGNIN = 'SIGNIN'
export const SETDATA = 'SETDATA'
export const SIGNOUT ='SIGNOUT'
export const SETUSER = 'SETUSER'
export const ADDERROR = 'ADDERROR'
export const CLEAN_ERROR ='CLEAN_ERROR'